### ISSUE TITLE
Getting error :network_failure

### ISSUE THREAD

**Issue by RobStallion** [fewlinesco/bamboo_smtp#107]
I am currently getting the following error on travis ci `{:network_failure, "[secure]", {:error, :timeout}}`. 

Below is my config...
```
config :bep, Bep.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: System.get_env("SES_SERVER"),
  port: 25,
  username: System.get_env("SMTP_USERNAME"),
  password: System.get_env("SMTP_PASSWORD"),
  tls: :always,
  ssl: false,
  retries: 1
```

And the full error is...

```
** (Bamboo.SMTPAdapter.SMTPError) There was a problem sending the email through SMTP.
     
The error is :retries_exceeded
     
More detail below:
     
{:network_failure, "[secure]", {:error, :timeout}}
```

I am not too sure what is causing this issue. What is really quite confusing is that the error appeared when no modifications had been made to the code. Branches that were once passing on Travis are now failing. 

Everything still works locally and in production so it seems like it could be an issue with Travis but any help would be appreciated.

**Comment by kdisneur** [comment]
Hi @RobStallion 

When I have this issue, it's either because my configuration is wrong (and I can't reach the SMTP server) or because of a network issue.

If you didn't change anything in your CI configuration or your SES configuration, I would try to add a `telnet` call to my SMTP server in the `travis.yml` configuration file, just to make sure the server is still reachable from travis. If it's not I would contact TravisCI support.

I have not much ideas besides this one.

**Comment by tgautier** [comment]
I'm closing this issue as it seems to be a configuration problem.

Feel free to reopen the issue if it's not the case.
