### ISSUE TITLE
 function :socket.connect/5 is undefined or private

### ISSUE THREAD

**Issue by tineo** [fewlinesco/bamboo_smtp#118]
Hi guys, I got this error with gen_smtp :(
`** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :socket.connect/5 is undefined or private
        (gen_smtp) :socket.connect(:tcp, 'email-smtp.us-east-1.amazonaws.com', 587, [:binary, {:packet, :line}, {:keepalive, true}, {:active, false}], 5000)
        (gen_smtp) /.../deps/gen_smtp/src/gen_smtp_client.erl:533: :gen_smtp_client.connect/2
        (gen_smtp)  /.../deps/gen_smtp/src/gen_smtp_client.erl:198: :gen_smtp_client.do_smtp_session/3
        (gen_smtp)  /.../deps/gen_smtp/src/gen_smtp_client.erl:143: :gen_smtp_client.try_smtp_sessions/4
        (bamboo_smtp) lib/bamboo/adapters/smtp_adapter.ex:77: Bamboo.SMTPAdapter.deliver/2
        (bamboo) lib/bamboo/mailer.ex:123: Bamboo.Mailer.deliver_now/3`

**Comment by kdisneur** [comment]
Hi. 

If you use OTP 22, you error might be related to https://github.com/fewlinesco/bamboo_smtp/issues/114

We updated our dependencies and we plan to publish the next version today. In the meantime you can try to use `master`. It's the same version as the one we will publish on hex.

If the problem is different, could you tell us which versions of these languages/libraries you use?
- OTP
- Elixir 
- bamboo_smtp
- gen_smtp

Thanks

**Comment by tineo** [comment]
Erlang/OTP 22 [erts-10.4] [source] [64-bit] 
Elixir 1.8.2 (compiled with Erlang/OTP 20)
bamboo 1.2.0
bamboo_smtp 1.6.0
gen_smtp 0.12.0

I'll use master. Thanks

**Comment by julien-leclercq** [comment]
@tineo you can use `1.7.0` in your `mix.exs`. I just published it
