### ISSUE TITLE
Subject character encoding

### ISSUE THREAD

**Issue by Lankester** [fewlinesco/bamboo_smtp#162]
When sending emails with version 3.1.0, my ASCII subject lines are displayed incorrectly in mail clients, for example: `H_Ui"bvu7`.

This seems to be related to the following call - https://github.com/fewlinesco/bamboo_smtp/blob/59dd51015bfa5ef752a41727692cf849182f865a/lib/bamboo/adapters/smtp_adapter.ex#L204-L210

Isn't `"=?UTF-8?B?#{content}?="` saying that this string is a UTF-8 character set, encoded in Base64 but without actually encoding the content in Base64?

Just returning `content` for only ASCII characters fixed my issue.

```
defp rfc822_encode(content) do 
   if contains_only_ascii_characters?(content) do 
     content
   else 
     "=?UTF-8?B?#{Base.encode64(content)}?=" 
   end 
 end 
```

**Comment by nabilallam** [comment]
Hi,
I faced the same issue.
as I understand `=?UTF-8?B?` means that the following text is base64 encoded. This should instruct the client to base64 decode the text. This means the solution should be:
```
defp rfc822_encode(content) do 
  "=?UTF-8?B?#{Base.encode64(content)}?="  
end 
```

I will create a MR with this solution. Please, clarify it for me, if you think I'm wrong.
thx

**Comment by nabilallam** [comment]
Also @Lankester solution should work.
What makes me uncertain is that the email sending is working with this code, where email adresses are delivered like this:
`=?UTF-8?B?nabil.allam@gmail.com?=" `
I'm not sure if it is working despite the wrong encoding information as they are fixing this problem or I don't understand something here.
If you have any advice. thx

**Comment by rzcastilho** [comment]
I'm facing the same issue.

**Comment by michelbieleveld** [comment]
Facing the same issue. According https://tools.ietf.org/html/rfc2047#section-4.2  even when only having ascii and using the Q encoding there are ascii characters that are not allowed and that must be encoded, = ? space and tab for example. 

@nabilallam Not sure but section 6.2 states "In the event other encodings are defined in the future, and the mail reader does not support the encoding used, it may either (a) display  the 'encoded-word' as ordinary text, or (b) substitute an appropriate message indicating that the text could not be decoded." 
So maybe that is why we are seeing the =?.. string  in the client as the encoding is not valid since only [0-9A-F] are valid.

Since the only benefit of implementing the Q encoding is for clients who only support us-ascii, the easiest solution is the proposal of nabilallam:

```
defp rfc822_encode(content) do
   "=?UTF-8?B?#{Base.encode64(content)}?="
end
```

Which solved the issue in my clients (postbox and gmail).

**Comment by arnaudmorisset** [comment]
Hello, and sorry for the delay. :sweat_smile: 

You're right.

It was an attempt to encode fewer headers to prevent spam prevention tools to marks many emails as undesirable. The more encoded headers you have, the more risks tools like SpamAssassin will mark them as spam. :sweat: 

Unfortunately, the meaning behind `=?UTF-8?B?` wasn't clear enough when we merged this update. Same thing for the link to the RFC shared by @michelbieleveld 

We will bring back the former implementation. Sorry for the inconvenience. 🙇‍♂️

**Comment by arnaudmorisset** [comment]
We merged the PR from @nabilallam and we released a new version of BambooSMTP: https://hex.pm/packages/bamboo_smtp/3.1.1

Please, let us know if everything is alright now. 🙂

**Comment by michelbieleveld** [comment]
@arnaudmorisset Thank you, that fixed the problem for me!
